FROM node:24-alpine
WORKDIR /workspace
RUN corepack enable

COPY package.json pnpm-workspace.yaml turbo.json prisma.config.js ./
COPY prisma ./prisma
COPY api/package.json api/package.json
COPY packages ./packages
COPY api ./api

RUN pnpm install --filter @template/api... --frozen-lockfile=false
RUN pnpm prisma generate
CMD ["node", "api/src/server.js"]
