#cloud-config
packages:
  - docker.io
  - docker-compose-plugin
runcmd:
  - mkdir -p /opt/stack-template
  - docker login -u ${dockerhub_username} --password-stdin </root/dockerhub.token
  - IMAGE_TAG=${image_tag} docker compose -f /opt/stack-template/docker-compose.deploy.yml up -d
